### PR TITLE
add common labels, annotation and security context to pods

### PR DESCRIPTION
**Pull request by ravisingal**

### CODE REVIEW

**Review by abeytom07 — APPROVED** [review]

**Comment by aaron-steinfeld** [comment]
let me update the locks to resolve these dep issues, one sec

**Comment by aaron-steinfeld** [comment]
Done. Can update branch

**Comment by ravisingal** [comment]
> Done. Can update branch

oh.. I also pushed it.

**Review by aaron-steinfeld — APPROVED** [review]
clean merge :)

**Pull request merged**
